//
//  SourceFileDecoratorTests.swift
//
//
//  Created by Stephen Anthony on 15/06/2023.
//

import XCTest
@testable import DJAStrings

final class SourceFileDecoratorTests: XCTestCase {
    private var sourceFileDecorator: SourceFileDecorator!
    private var vendedDecoratedContent: String!
    
    override func tearDown() {
        sourceFileDecorator = nil
        vendedDecoratedContent = nil
        super.tearDown()
    }
    
    func testItDecoratesTheFileContentsCorrectlyWhenAddingAttributionDocumentation() {
        givenASourceFileDecorator()
        whenTheSourceFileDecoratorIsAskedToAddAttributionDocumentation(toFilenameAndExtension: "Test.swift", fileContents: "Test Content")
        let expectedOutput = """
//
//  Test.swift
//
//
//  Generated by DJAStrings.
//

Test Content
"""
        XCTAssertEqual(vendedDecoratedContent, expectedOutput)
    }
    
    private func givenASourceFileDecorator() {
        sourceFileDecorator = SourceFileDecorator()
    }
    
    private func whenTheSourceFileDecoratorIsAskedToAddAttributionDocumentation(toFilenameAndExtension filenameAndExtension: String, fileContents: String) {
        vendedDecoratedContent = sourceFileDecorator.addAttributionDocumentation(forFilenameAndExtension: filenameAndExtension, sourceFileContents: fileContents)
    }
}
