//
//  SourceFileDecorator.swift
//
//
//  Created by Stephen Anthony on 15/06/2023.
//

import Foundation

/// Allows the contents of source files to be decorated.
final class SourceFileDecorator {
    
    /// Adds attribution documentation to the header of the given source file
    /// contents.
    /// - Parameters:
    ///   - filenameAndExtension: The name and extension of the file that the
    ///   contents will be written to.
    ///   - sourceFileContents: The source file's contents.
    /// - Returns: The given source file's contents, decorated with a header
    /// containing the given filename and extension.
    func addAttributionDocumentation(forFilenameAndExtension filenameAndExtension: String, sourceFileContents: String) -> String {
        """
//
//  \(filenameAndExtension)
//
//
//  Generated by DJAStrings.
//

\(sourceFileContents)
"""
    }
}
